version: '3.8'
services:
  contas-pagar:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "9000:9000"
    environment:
      # POSTGRES
      - DATASOURCE_URL:jdbc:postgresql://db:5432/contas_pagar
      - DATASOURCE_USERNAME:postgres
      - DATASOURCE_PASSWORD:root
      # RABBITMQ
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=contas_pagar
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3.8.2-management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'